version: '3.4'
services:

  storybook:
    build: .
    working_dir: /home/node
    volumes:
      - .:/home/node:delegated
      - /home/node/node_modules
    environment:
      PORT: 8001
    ports: ["8001:8001"]
